# This workflow will build a Swift project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-swift

name: Run Tests

on:
  pull_request:
    branches:
      - main

jobs:
  tests:
    runs-on: macos-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          - name: Codecs
            suite: MLXAudioTests/MLXAudioCodecsTests
          - name: TTS
            suite: MLXAudioTests/MLXAudioTTSTests
          - name: STT
            suite: MLXAudioTests/MLXAudioSTTTests
          - name: VAD
            suite: MLXAudioTests/MLXAudioVADTests

    steps:
      - uses: actions/checkout@v4
      - name: Select Xcode version
        uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: 'latest'
      - name: Install Metal toolchain
        run: xcodebuild -downloadComponent MetalToolchain
      - name: Build
        run: xcodebuild build-for-testing -scheme MLXAudio-Package -destination 'platform=macOS' MACOSX_DEPLOYMENT_TARGET=14.0 CODE_SIGNING_ALLOWED=NO
      - name: Run ${{ matrix.name }} tests
        run: xcodebuild test-without-building -scheme MLXAudio-Package -destination 'platform=macOS' -only-testing:${{ matrix.suite }} CODE_SIGNING_ALLOWED=NO
